### ISSUE TITLE
Analysis does not respect <inheritdoc />

### ISSUE THREAD

**Issue by dittodhole** [CSharpAnalyzers/ExceptionalReSharper#65] opened 2017-09-06 08:14 UTC
Following code given:

```csharp
using System;
using JetBrains.Annotations;

public abstract class Base
{
  /// <exception cref="ArgumentNullException"><paramref name="arg" /> is <see langword="null" /></exception>
  protected Base([NotNull] string arg)
  {
    this.Arg = arg ?? throw new ArgumentNullException(nameof(arg));
  }

  [NotNull]
  public string Arg { get; }
}

public class Child : Base
{
  /// <inheritdoc />
  public Child([NotNull] string arg)
   : base (arg) { }
}
```

This construct gives me an analysis-error for `Child`: _Exception 'ArgumentNullException' is not documented [Exceptional]_

**Comment by RSuter** [comment] 2017-09-06 08:15
Duplicate of https://github.com/CSharpAnalyzers/ExceptionalReSharper/issues/26

**Closed** 2017-09-06 20:42 UTC
Labels: enhancement
