### ISSUE TITLE
Exceptional gives warnings about missing exception documentation when method implements interface with <inheritdoc/> tag

### ISSUE THREAD

**Issue by alexmarshall132** [CSharpAnalyzers/ExceptionalReSharper#32] opened 2016-03-14 22:06 UTC
Exceptional gives a warning about an exception not being in method documentation when the following criteria are met:
1) method implements an interface
2) method has an <inheritdoc /> documentation tag
3) the corresponding interface method documentation documents the exception.

Recommended behavior in this case is to provide no error as the exception has been documented. Users can simply click on the (i) icon in the well to go to the interface or use the keyboard shortcuts provided by Resharper to navigate to the interface and see the documentation.

**Comment by Xilconic** [comment] 2018-02-26 05:55
I can confirm that this problem still exists as of ExceptionalResharper v0.12.0 using Resharper Ultimate v2017.3.1.

Reproduction:
Abstract class A with abstract void Foo() that documents to throw an exception, for instance InvalidOperationException. Concrete class B inherits from A, and implements override of Foo() to throw InvalidOperationException. In B, marking Foo() with <inheritdoc /> will not remove the squigly marker on 'new InvalidOperationException()'.

**Comment by ManticSic** [comment] 2020-02-06 09:57
Duplicate of #26, #65 and #73

**Closed by ManticSic** 2020-02-06 09:57 UTC
