### ISSUE TITLE
The Tag <inheritdoc> was not considered.

### ISSUE THREAD

**Issue by arpef** [CSharpAnalyzers/ExceptionalReSharper#26] opened 2015-12-03 09:13 UTC
The exception in class Modul has squiggles. Here was not supported the inheritdoc tag.

example:

```
public interface IModul
{
    /// <summary />
    /// <exception cref="ArgumentNullException"><paramref name="mainMenu"/> is <see langword="null" />.</exception>
    void SetMainMenu(MenuStrip mainMenu);
}

public class Modul : IModul
{
    /// <inheritdoc />
    public void SetMainMenu(MenuStrip mainMenu)
    {
        if (mainMenu == null)
        {
            throw new ArgumentNullException("mainMenu");
        }
    }
}
```

**Comment by cmeeren** [comment] 2017-02-23 18:15
I too would like `<inheritdoc />` to be considered by Exceptional.

**Comment by ManticSic** [comment] 2020-02-06 09:58
Duplicate of #32, #65 and #73

**Closed by ManticSic** 2020-02-06 09:58 UTC
Labels: enhancement
